# Aprendendo conceitos iniciais sobre o Tensorflow

In [1]:
import tensorflow as tf
import numpy as np

### Constantes Tensorflow

In [7]:
constant = tf.constant([[23, 4], [32, 51]])

In [8]:
constant

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [9]:
# Forma 2 linhas e 2 colunas
constant.shape

TensorShape([2, 2])

In [10]:
constant.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

> O Tensorflow e o NumPy estão integrados, então um pode virar o outro

### Váriaveis Tensorflow

In [13]:
variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [14]:
variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operações com tensores

In [15]:
constant + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25,  6],
       [34, 53]], dtype=int32)>

In [16]:
constant * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 69,  12],
       [ 96, 153]], dtype=int32)>

In [17]:
np.square(constant)

array([[ 529,   16],
       [1024, 2601]], dtype=int32)

In [18]:
np.sqrt(constant)

array([[4.79583152, 2.        ],
       [5.65685425, 7.14142843]])

In [20]:
# Multiplicação entre matrizes
# np.dot(matriz, outra_matriz)

### Strings no Tensorflow

In [22]:
tf_string = tf.constant("Tensorflow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

In [23]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [24]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>